# ==========================================================================
# Configmaps:
#   assets
#   carts
#   catalog
#   checkout
#   orders
#   ui
# (6)
# ==========================================================================
# Source: retail-store-sample-assets-chart/templates/configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: assets
data:
  PORT: '8080'
---
# Source: retail-store-sample-cart-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: carts
data:
  SPRING_PROFILES_ACTIVE: dynamodb
  CARTS_DYNAMODB_TABLENAME: Items
  CARTS_DYNAMODB_CREATETABLE: "false"
  CARTS_DYNAMODB_CREATETABLE: "true"
  AWS_ACCESS_KEY_ID: key
  AWS_SECRET_ACCESS_KEY: secret
  CARTS_DYNAMODB_ENDPOINT: http://carts-dynamodb:8000
---
# Source: retail-store-sample-catalog-chart/templates/configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog
data:
  DB_ENDPOINT: catalog-mysql:3306
  DB_READ_ENDPOINT: catalog-mysql:3306
  DB_NAME: catalog
---
# Source: retail-store-sample-checkout-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout
data:
  REDIS_URL: redis://checkout-redis:6379
  ENDPOINTS_ORDERS: http://orders:80
---
# Source: retail-store-sample-orders-chart/templates/configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders
data:
  RETAIL_ORDERS_MESSAGING_PROVIDER: rabbitmq
  SPRING_DATASOURCE_URL: jdbc:postgresql://orders-postgresql:5432/orders
  SPRING_RABBITMQ_ADDRESSES: amqp://orders-rabbitmq:5672
---
# Source: retail-store-sample-ui-chart/templates/configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui
data:
  
  ENDPOINTS_CATALOG: http://catalog
  ENDPOINTS_CARTS: http://carts
  ENDPOINTS_CHECKOUT: http://checkout
  ENDPOINTS_ORDERS: http://orders
  ENDPOINTS_ASSETS: http://assets