# ==========================================================================
# Secrets:
#   catalog-db
#   orders-db
#   orders-rabbitmq
# (3)
# ==========================================================================
# Source: retail-store-sample-catalog-chart/templates/mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: catalog-db
data:
  username: "Y2F0YWxvZw=="
  password: "NVlGTWRva2taTWVDeWhpaw=="
---
# Source: retail-store-sample-orders-chart/templates/postgresql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: orders-db
data:
  username: "b3JkZXJz"
  password: "QTRZNWY4Q1djU1hZaWloYw=="
---
# Source: retail-store-sample-orders-chart/templates/rabbitmq-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: orders-rabbitmq
data: